### ISSUE TITLE
Attribute access to multi-value entries should give a list

### ISSUE THREAD

**Issue by htgoebel** [eventable/vobject#81]
Currently attribute access to multi-value entries always return a single entry.
```
>>> j = vobject.vCard()
>>> j.add('email').value = 'jeffrey@osafoundation.org'
>>> j.add('email').value = "susan@example.com"
>>> j.email
<EMAIL{}jeffrey@osafoundation.org>
```

While this is convenient if a vCard contains a single e-mail-address (or tel, etc.), this is gives a wrong notion about what these entries are. Esp. this leads to an asymmetric behavior, since for accessing a entries, one needs to use a completely different way to access:
```
>>> v.fn
<FN{}Jeffrey Harris>
>>> v.tel
<TEL{'TYPE': ['WORK', 'VOICE']}(111) 555-1212>
>>> v.contents['tel']
[<TEL{'TYPE': ['WORK', 'VOICE']}(111) 555-1212>, <TEL{'TYPE': ['HOME', 'VOICE']}(404) 555-1212>]
```

**What would you expect**

I'd expect the `tel` attribute (and `email`, etc.) to return a list:
```
>>> v.tel
[<TEL{'TYPE': ['WORK', 'VOICE']}(111) 555-1212>, <TEL{'TYPE': ['HOME', 'VOICE']}(404) 555-1212>]
```

**Comment by wpercy** [comment]
So the correct way to do this is actually to append `_list` to the end of the property name when using `__getattr__`. So to do this with `email` like you try to do above, it would look like: 

    >>> j = vobject.vCard()
    >>> j.add('email').value = 'jeffrey@osafoundation.org'
    >>> j.add('email').value = "susan@example.com"
    >>> j.email_list
    [<EMAIL{}jeffrey@osafoundation.org>, <EMAIL{}susan@example.com>]

Yes, this requires some knowledge of the vCard (or vCalendar as the case may be) properties because you need to know which ones are potentially multi-valued, but you can also access single-value properties like `FN` using this notation as well, it will just return a single-element list.

    >>> j = vobject.vCard()
    >>> j.add('fn').value = 'Will Percival'
    >>> j.fn_list
    [<FN{}Will Percival>]
