### ISSUE TITLE
Question: What Python type is parsed VCard? Custom dictionary?

### ISSUE THREAD

**Issue by minthemiddle** [eventable/vobject#9]
When I parse a VCard via `v = readOne(s)`\- of course after defining the VCard (see below) and importing the right module via `from vobject import vCard, readOne`, I get an object that I have no clue what Python type it is.

`v.contents` looks a lot like a dictionary, but I do not understand what the `<XXX` parts in it mean.

V.CONTENTS

```
{'adr': [<ADR{'TYPE': ['HOME', 'pref']}
  Berlin, Berlin 
  Germany>],
 'bday': [<BDAY{}1986-11-17>],
 'email': [<EMAIL{'TYPE': ['INTERNET', 'HOME', 'pref']}xxx@gmail.com>],
 'fn': [<FN{}XX XX>],
 'n': [<N{}   XXX >],
 'prodid': [<PRODID{}-//Apple Inc.//Mac OS X 10.11.3//EN>],
 'tel': [<TEL{'TYPE': ['CELL', 'VOICE', 'pref']}+4915773321986>],
 'uid': [<UID{}e0355606-117f-4388-bb6d-eda3a1f6449d>],
 'version': [<VERSION{}3.0>],
 'x-abuid': [<X-ABUID{}E0355606-117F-4388-BB6D-EDA3A1F6449D:ABPerson>]}
```

VCARD

```
s = """
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Mac OS X 10.11.3//EN
N:XXX;;;
FN:XX XX
EMAIL;type=INTERNET;type=HOME;type=pref:xxx@gmail.com
TEL;type=CELL;type=VOICE;type=pref:+4915773321986
ADR;type=HOME;type=pref:;;;Berlin;Berlin;;Germany
BDAY:1986-11-17
UID:e0355606-117f-4388-bb6d-eda3a1f6449d
X-ABUID:E0355606-117F-4388-BB6D-EDA3A1F6449D:ABPerson
END:VCARD
"""
```

**Comment by wpercy** [comment]
@minthemiddle The X's come from the "N" and "FN" (name and full name) lines of the vCard.

`v.contents` does indeed return the native Python `dict` type - each key relates to a property of the vCard, and each value is the appropriate line(s) of the vCard.

So for example, the 'n' key contains the value for NAME, which, in your vCard, takes the value of `XXX;;;` - that's why that's what shows up as the value in the dict. The empty dictionary (`{}`) is there because there are no associated params with the `N` field. If you look at `TEL`, which does include params, you can see that the dictionary is populated with those params. I hope that helps!
